### ISSUE TITLE
Projection operation in Fig.1

### ISSUE THREAD

**Issue by zheng547** [samuel930930/Dual_Manifold_Adversarial_Training#1]
![image](https://user-images.githubusercontent.com/54466644/163088465-f294ac46-82f7-45bd-b786-6e946b6964e3.png)

I could not find the position of relating projection operation codes in the project. Could you point it out? 

Thanks.

**Comment by samuel930930** [comment]
The projection described in Fig. 1 is GAN inversion, which is computationally costly. Therefore, we preprocess all the images and save all the corresponding latent vectors and construct the proposed OM-ImageNet dataset. Hence, there is no code about the projection operation.
